- name: Secure Server
  hosts: localhost
  become: yes

  tasks:
  - name: Allow SSH
    ufw: 
      rule: allow 
      port: 22 
      proto: tcp

  - name: Set firewall default policy
    ufw: 
      state: enabled 
      policy: reject

  - name: install Fail2Ban
    apt:
      pkg:
      - fail2ban
      update_cache: yes
      state: present

  - name: Enable Fail2Ban
    service:
      name: fail2ban
      enabled: yes
      state: started

  - name: Install auto updates
    apt:
      pkg:
      - unattended-upgrades
      - apt-listchanges
      update_cache: yes
      state: present
  
  - name: Enable auto updates
    service:
      name: unattended-upgrades
      enabled: yes
      state: started 