- name: Install Docker
  hosts: localhost
  become: yes

  tasks:
  - name: install dependencies
    apt:
      pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      update_cache: yes
      state: present

  - name: add pgp key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add repo
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present 

  - name: install docker runtime
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - docker-compose
      update_cache: yes
      state: present